@@include('../../node_modules/jquery/dist/jquery.min.js');
@@include('../../node_modules/slick-carousel/slick/slick.min.js');
@@include('../../node_modules/picturefill/dist/picturefill.min.js');
@@include('vendors/webp-check.js');
@@include('vendors/smooth-scroll.js');
@@include('modules/faq-questions.js');
@@include('modules/pets-slider.js');
@@include('modules/team-slider.js');
@@include('modules/reviews-slider.js');
